apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: wanderlust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: prajwalkumar1453/frontend:v5.1
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_PATH
              value: http://backend-service:8080
