apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: wanderlust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: prajwalkumar1453/frontend-local:v4
          # image: front-local:test
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_PATH
              value: 'http://localhost:8080'
