apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
  namespace: wanderlust
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis-service
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data/redis
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
